language: node_js
node_js:
  - "11.1.0"
install:
  - cd lib
  - tar -xvf GraphicsMagick-1.3.35.tar.gz
  - cd GraphicsMagick-1.3.35
  - ./configure --prefix=/home/travis
  - make
  - make install
  - cd ..
  - npm install
script:
  - npm run build
